name: Run Linter

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: { dir: ["./"] }

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Install modules
        working-directory: ${{ matrix.dir }}
        run: rm -rf node_modules && npm install
      - name: Install ESLint
        working-directory: ${{ matrix.dir }}
        run: npm i eslint
      - name: Run ESLint
        working-directory: ${{ matrix.dir }}
        run: npx eslint ./**/*.{js,ts,tsx} --quiet --no-error-on-unmatched-pattern
