name: Run Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: { node-version: [12.x, 14.x, 16.x] }
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: "npm"
      - name: Install dependencies
        run: npm i
      - name: Run Test
        run: npm run test
